### ISSUE TITLE
Unitary tests for d_finder

### ISSUE THREAD

**Issue by FPitscheider** [dcascade-py/dcascade-py#39]
GSD calculated by the d_finder does not match the expected. In the test we give values for fi_r 0.25, 0.35, 0.25, 0.15 (from fine to coarse).
For D25, D_finder gives the dmi value corresponding to the 0.25 percentage, for D60, it gives the value associated to the 0.35 percentage (0.25+0.35 = 0.6). This is valid also for the D85 and 85 percentage.
D100 bugs. 
We don't understand the interpolation in-between. We tried D12.5 and expected half of D25, whereas that was not the case. The same goes with D42.5 (middle between D25 and D60).

**Comment by didoolaeghe** [comment]
Why do you expect half of D25 ? It can be different since it depends on the shape of the curve that fits the 4 sediment sizes. 
Which value did you get ? And what did you get for D50 ?

**Comment by ALArgentin** [comment]
Ok, so that was because the interpolation is done in log space (which is correct) and not in linear space. This was added to the documentation.
